development:
  adapter: postgresql
  encoding: utf8
  database: firma1c
  username: master
  password: ahbplf22
  pool: 5 # not mandatory
  timeout: 5000 # not mandatory
  host: localhost



test:
  database: firma1c
  username: master
  password: ahbplf22

production:
  database: firma1c_prod
  username: deploy
  password: ahbplf22
